# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-05 08:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='上次修改时间')),
                ('content', tinymce.models.HTMLField(verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='类型id')),
                ('type', models.CharField(max_length=100, verbose_name='文章类型')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='评论编号')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('art_cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Article', verbose_name='评论文章')),
                ('null', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Comment', verbose_name='评论')),
                ('user_cont', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户评论')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('age', models.CharField(blank=True, max_length=200, null=True, verbose_name='用户年龄')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户性别')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='联系方式')),
                ('addr', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户地址')),
                ('img', models.ImageField(default='static/imgs/default.png', upload_to='static/imgs/', verbose_name='用户头像')),
                ('user', models.OneToOneField(on_delete=models.Model, to=settings.AUTH_USER_MODEL, verbose_name='关联')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ArticleType', verbose_name='所属类型'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
